from django.shortcuts import render

def home(request):
    return render(request, 'index.html')

def count_nucleobases(dna):
    
    string = "ATCTAGGAACTCGTCTTTAGTAGCGTATTGTTCCGCTGGAAGACCGTCGTTCCTGAATCGAGAGAGTCTTGGCACCCGAGCCGGATATAAGGTCTGTATAGCAACAAGTTGTGCGGCAGTGAGGATTACTAACATATGTATTTATAATTTTCCTGTAAAAGCATTGTCCGGCTGTCGAAGAATCGCTGTAGCCCATGGAGGGTGTCAGGGATACGCGTTACCCAACCATATTGCTCTCCCGAATCAGATCTAGTTACTACTCGTGAAGGCACAAGAGAATTCTATTGACGATGGTCAGAGCTCACCCGCGTGGTCTGCAGTCTTCGACCCCAACACTTAAGACCTATGGTCGGCTCATAGAACCAGCTTGGTGATTAAGTCAGAGGGGCCACACTTATGTAAGCGCGATAAAACGGGGCGATCGTCGAACACTAGCCCACGAAAACTGCCGCTTACCAGCATGGAACATTGATCTCAGAGCAGTACAGCTCGCCGCTGAACCCAATTTTGTGATATGATAAACAGCATGCAGGCGGTTACTGTGGTGCGCAGCCTTCTGAGCCAGCCGTAAGCCATGATGATAGAGGACAGAATGTGGTCGCCCATCTGCGCCTCGGGTGAGACCGCTGGATAGGAGGAAGACCACACACTCAGCCAGGGGGAACGGAAAAGTGACACGTCCCGTCAACCTTCTTCCGTCGCTATGCCACTTCTTCTCCAAACTAAAGCGGAAGAATAATTAATACGTTCAATAGCCGAACGCGGGTGGGACCGGGTTCATACCTGCGTTTATAAGATGACGTCACAAATTCCAACGGTACGATTTTTGGCTTGTTGCGCACCAATTGTCTTTCAATGTCCCGTGCTAGTGTGTGGGCTGACGTGGTTGCCCCCTAAGACGAGCTAAGGGCATTCGCGCAGGGCGTCCGACTAACGCCGCAATAATGATACGATGATCGGCGACGTCATGCTTGGATCGTGCCACAATCCGGA"

    adenine = 0
    thymine = 0
    cytosine = 0
    guanine = 0
    for letter in string:
        if(letter == 'A'):
            adenine+=1
        elif(letter == 'T'):
            thymine+=1
        elif(letter == 'C'):
            cytosine+=1
        elif(letter == 'G'):
            guanine+=1

    count = [adenine,cytosine,guanine,thymine,]